version: "3.8"

services:
  web:
    # build: ./app  # Ищет Dockerfile
    build:
      context: ./app  # path
      dockerfile: Dockerfile.prod  # имя явно Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    # Expose делает порт доступен только внутри других сервисов docker, не внешние
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80  # 1337:80(http)
    depends_on:
      - web

volumes:
  postgres_data: